/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anton
 */
public class GestionBaseDatos extends javax.swing.JFrame {
    private GestionProfesor gp;
    private GestionCarreras gc;
    private GestionDatosLaborales gdl;
    private GestionDatosAcademicos gda;
    private GestionCA gca;
    private GestionAsignaturas ga;
    private GestionLGAC glgac;
    private GestionDireccionIndividualizada gdi;
    /**
     * Creates new form GestionProfesor
     */
    public GestionBaseDatos() {
        initComponents();
        gp=new GestionProfesor(this,true);
        gc=new GestionCarreras(this,true);
        gdl=new GestionDatosLaborales(this,true);
        gda=new GestionDatosAcademicos(this,true);
        gca=new GestionCA(this,true);
        ga=new GestionAsignaturas(this,true);
        glgac=new GestionLGAC(this,true);
        gdi=new GestionDireccionIndividualizada(this,true);
        
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnProfesor = new javax.swing.JButton();
        btnCarreras = new javax.swing.JButton();
        btnDatosLaborales = new javax.swing.JButton();
        btnAsignaturas = new javax.swing.JButton();
        btnDatosAcademicos = new javax.swing.JButton();
        btnLGAC = new javax.swing.JButton();
        btnCA = new javax.swing.JButton();
        btnProduccionAcademica = new javax.swing.JButton();
        btnProyectosInvestigacion = new javax.swing.JButton();
        btnDireccionIndividualizada = new javax.swing.JButton();
        btnTutoria = new javax.swing.JButton();
        btnGestionAV = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5), "Base de datos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        btnProfesor.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnProfesor.setText("Profesor");
        btnProfesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProfesorMouseClicked(evt);
            }
        });
        btnProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfesorActionPerformed(evt);
            }
        });

        btnCarreras.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnCarreras.setText("Carreras");
        btnCarreras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCarrerasMouseClicked(evt);
            }
        });

        btnDatosLaborales.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnDatosLaborales.setText("Datos laborales");
        btnDatosLaborales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDatosLaboralesMouseClicked(evt);
            }
        });

        btnAsignaturas.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnAsignaturas.setText("Asignaturas");
        btnAsignaturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAsignaturasMouseClicked(evt);
            }
        });

        btnDatosAcademicos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnDatosAcademicos.setText("Datos academicos");
        btnDatosAcademicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDatosAcademicosMouseClicked(evt);
            }
        });
        btnDatosAcademicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosAcademicosActionPerformed(evt);
            }
        });

        btnLGAC.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnLGAC.setText("LGAC");
        btnLGAC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLGACMouseClicked(evt);
            }
        });

        btnCA.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnCA.setText("CA");
        btnCA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCAMouseClicked(evt);
            }
        });

        btnProduccionAcademica.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnProduccionAcademica.setText("Produccion academica");
        btnProduccionAcademica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduccionAcademicaActionPerformed(evt);
            }
        });

        btnProyectosInvestigacion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnProyectosInvestigacion.setText("Proyectos de investigacion");

        btnDireccionIndividualizada.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnDireccionIndividualizada.setText("Direccion individualizada");
        btnDireccionIndividualizada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDireccionIndividualizadaMouseClicked(evt);
            }
        });

        btnTutoria.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnTutoria.setText("Tutoria/Asesoria");

        btnGestionAV.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnGestionAV.setText("Gestion AV");

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel1.setText("Selecciona una tabla");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnProfesor)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnCarreras))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnAsignaturas)
                            .addGap(27, 27, 27)
                            .addComponent(btnLGAC))
                        .addComponent(jLabel1))
                    .addComponent(btnProyectosInvestigacion))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnDatosLaborales)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnDatosAcademicos)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnCA))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(btnDireccionIndividualizada)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTutoria)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGestionAV)
                        .addGap(47, 47, 47)
                        .addComponent(btnProduccionAcademica)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProfesor)
                    .addComponent(btnCarreras)
                    .addComponent(btnDatosLaborales)
                    .addComponent(btnDatosAcademicos)
                    .addComponent(btnCA))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAsignaturas)
                    .addComponent(btnLGAC)
                    .addComponent(btnDireccionIndividualizada)
                    .addComponent(btnTutoria))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProyectosInvestigacion)
                    .addComponent(btnGestionAV)
                    .addComponent(btnProduccionAcademica))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProfesorActionPerformed

    private void btnProfesorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfesorMouseClicked
        gp.setLocationRelativeTo(null);
        gp.setVisible(true);
    }//GEN-LAST:event_btnProfesorMouseClicked

    private void btnProduccionAcademicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduccionAcademicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProduccionAcademicaActionPerformed

    private void btnDatosAcademicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosAcademicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDatosAcademicosActionPerformed

    private void btnCarrerasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCarrerasMouseClicked
        gc.setLocationRelativeTo(null);
        gc.setVisible(true);
    }//GEN-LAST:event_btnCarrerasMouseClicked

    private void btnDatosLaboralesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDatosLaboralesMouseClicked
        gdl.setLocationRelativeTo(null);
        gdl.setVisible(true);
    }//GEN-LAST:event_btnDatosLaboralesMouseClicked

    private void btnDatosAcademicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDatosAcademicosMouseClicked
        gda.setLocationRelativeTo(null);
        gda.setVisible(true);
    }//GEN-LAST:event_btnDatosAcademicosMouseClicked

    private void btnCAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCAMouseClicked
        gca.setLocationRelativeTo(null);
        gca.setVisible(true);
    }//GEN-LAST:event_btnCAMouseClicked

    private void btnAsignaturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAsignaturasMouseClicked
        ga.setLocationRelativeTo(null);
        ga.setVisible(true);
    }//GEN-LAST:event_btnAsignaturasMouseClicked

    private void btnLGACMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLGACMouseClicked
        glgac.setLocationRelativeTo(null);
        glgac.setVisible(true);
    }//GEN-LAST:event_btnLGACMouseClicked

    private void btnDireccionIndividualizadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDireccionIndividualizadaMouseClicked
        gdi.setLocationRelativeTo(null);
        gdi.setVisible(true);
    }//GEN-LAST:event_btnDireccionIndividualizadaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionBaseDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionBaseDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionBaseDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionBaseDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionBaseDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignaturas;
    private javax.swing.JButton btnCA;
    private javax.swing.JButton btnCarreras;
    private javax.swing.JButton btnDatosAcademicos;
    private javax.swing.JButton btnDatosLaborales;
    private javax.swing.JButton btnDireccionIndividualizada;
    private javax.swing.JButton btnGestionAV;
    private javax.swing.JButton btnLGAC;
    private javax.swing.JButton btnProduccionAcademica;
    private javax.swing.JButton btnProfesor;
    private javax.swing.JButton btnProyectosInvestigacion;
    private javax.swing.JButton btnTutoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
